export ROS_DOMAIN_ID=0
# export ROS_LOCALHOST_ONLY=0
export ROS_AUTOMATIC_DISCOVERY_RANGE=SUBNET
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp

export ROS_SUPER_CLIENT=True
export ROS_DISCOVERY_SERVER="192.168.79.228:11811;"

# export FASTRTPS_DEFAULT_PROFILES_FILE=$HOME/${WS_DIR}/config/fastdds_mrc.xml
